//! Service keyring: the single **notary** role that signs every
//! snapshot statement. All real cryptography flows through
//! [`unidpp_signatif`]; this module owns the seed bytes and the
//! derived [`unidpp_signatif::keyring::KeyPair`] handle.
//!
//! One role, on purpose: the archive's signature lives **inside**
//! each archival document (the AIP is self-verifying), unlike
//! `unidpp-trust`'s per-response header signing with two suites. The
//! task register pins the notarization to Ed25519 in the tree-head
//! domain — the same adapter note as `unidpp-trust`.
//!
//! Mode resolution:
//!
//! - **env-key mode**: `UNIDPP_ARCHIVE_SIGN_SEED` set to hex of at
//!   least [`MIN_SEED_BYTES`] bytes. The raw bytes become the signing
//!   seed (production keeps the CSPRNG outside this crate).
//! - **seeded-dev mode**: seed unset or rejected. The service derives
//!   the key deterministically from a single human-readable dev seed
//!   (`UNIDPP_ARCHIVE_DEV_SEED`, else a fixed default) — same seed
//!   always produces the same keyring, so tests and restart replay
//!   stay reproducible. The `/keyring` "warning" field tells
//!   operators which mode they are in.

use serde_json::{json, Value};
use unidpp_signatif::keyring::{KeyPair, PublicKey};
use unidpp_signatif::sign::Suite;

use crate::hex::{hex_decode, hex_encode};

/// The fallback dev seed when `UNIDPP_ARCHIVE_DEV_SEED` is unset.
/// Never used in production deployments (env-key mode overrides it).
pub const DEFAULT_DEV_SEED: &str = "unidpp-archive/dev-1";

/// Minimum decoded seed length (hex-encoded minimum 16 bytes — short
/// material is rejected to avoid accidentally-weak dev seeds).
pub const MIN_SEED_BYTES: usize = 16;

/// How the keyring was assembled — exposed to operators via `/keyring`
/// and the discovery document.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum KeyringMode {
    /// Deterministic key derived from a fixed seed (dev mode only;
    /// never use in production).
    SeededDev,
    /// Key loaded from an environment-supplied hex seed.
    EnvKey,
}

impl KeyringMode {
    pub fn as_str(self) -> &'static str {
        match self {
            KeyringMode::SeededDev => "seeded-dev",
            KeyringMode::EnvKey => "env-key",
        }
    }
}

/// The archive's notary keyring. Construct via [`Keyring::dev`] or
/// [`Keyring::from_env_seed`].
#[derive(Debug)]
pub struct Keyring {
    mode: KeyringMode,
    notary_key: KeyPair,
    /// The human-readable seed that produced this keyring (only set
    /// in seeded-dev mode — env-key mode reports `None`).
    dev_seed: Option<String>,
}

impl Keyring {
    /// Deterministic dev-mode keyring derived from `seed`. When
    /// `seed.is_empty()`, falls back to [`DEFAULT_DEV_SEED`].
    pub fn dev(seed: Option<&str>) -> Keyring {
        let dev_seed = match seed {
            Some(s) if !s.trim().is_empty() => s.trim().to_string(),
            _ => DEFAULT_DEV_SEED.to_string(),
        };
        let material = format!("unidpp-archive/notary|{dev_seed}");
        // KeyPair::seeded only errors for deferred suites (Sm2/MlDsa);
        // Ed25519 always succeeds — unwrap is safe by construction.
        let notary_key =
            KeyPair::seeded(Suite::Ed25519, material.as_bytes()).expect("Ed25519 seed derivation");
        Keyring {
            mode: KeyringMode::SeededDev,
            notary_key,
            dev_seed: Some(dev_seed),
        }
    }

    /// Env-key mode: raw seed supplied by the operator (typically
    /// generated by a separate CSPRNG-backed ceremony and pasted as
    /// hex). Required to decode to at least [`MIN_SEED_BYTES`] bytes.
    pub fn from_env_seed(ed_hex: &str) -> Result<Keyring, String> {
        let seed = hex_decode(ed_hex.trim()).map_err(|e| format!("notary seed: not hex: {e}"))?;
        if seed.len() < MIN_SEED_BYTES {
            return Err(format!(
                "notary seed too short: {} bytes (need at least {MIN_SEED_BYTES})",
                seed.len()
            ));
        }
        let notary_key = KeyPair::seeded(Suite::Ed25519, &seed)
            .map_err(|e| format!("Ed25519 key derivation: {e}"))?;
        Ok(Keyring {
            mode: KeyringMode::EnvKey,
            notary_key,
            dev_seed: None,
        })
    }

    /// Resolve a keyring from environment variables. Bad seeds are
    /// reported via the returned warnings; on any failure the service
    /// falls back to deterministic dev mode.
    pub fn from_env(dev_seed: Option<&str>) -> (Keyring, Vec<String>) {
        let mut warnings = Vec::new();
        match std::env::var("UNIDPP_ARCHIVE_SIGN_SEED").ok() {
            Some(seed) if !seed.trim().is_empty() => match Keyring::from_env_seed(&seed) {
                Ok(k) => (k, warnings),
                Err(err) => {
                    warnings.push(format!(
                        "UNIDPP_ARCHIVE_SIGN_SEED rejected: {err}; falling back to seeded-dev mode"
                    ));
                    (Keyring::dev(dev_seed), warnings)
                }
            },
            _ => (Keyring::dev(dev_seed), warnings),
        }
    }

    pub fn mode(&self) -> KeyringMode {
        self.mode
    }

    pub fn dev_seed(&self) -> Option<&str> {
        self.dev_seed.as_deref()
    }

    /// The notary key pair (signing handle).
    pub fn notary(&self) -> &KeyPair {
        &self.notary_key
    }

    /// The notary public key (what verifiers pin).
    pub fn public(&self) -> &PublicKey {
        self.notary_key.public()
    }

    /// Content-derived key id of the notary key.
    pub fn key_id(&self) -> &unidpp_signatif::keyring::KeyId {
        self.notary_key.key_id()
    }

    /// Hex-encoded raw public key bytes (32 bytes for Ed25519).
    pub fn public_hex(&self) -> String {
        hex_encode(self.public().as_bytes())
    }

    /// Public view for `/keyring`: mode, suite, key id, the hex
    /// public anchor a verifier pins, and the verification recipe
    /// matching the document's provenance section.
    pub fn to_json(&self) -> Value {
        let mut m = serde_json::Map::new();
        m.insert("mode".into(), json!(self.mode.as_str()));
        m.insert("role".into(), json!("notary"));
        m.insert("suite".into(), json!(self.notary_key.suite().as_str()));
        m.insert("key_id".into(), json!(self.key_id().to_string()));
        m.insert("public".into(), json!(self.public_hex()));
        m.insert("public_len".into(), json!(self.public().as_bytes().len()));
        m.insert("domain".into(), json!("tree-head"));
        m.insert("adapter_note".into(), json!(crate::model::ADAPTER_NOTE));
        m.insert(
            "verification".into(),
            json!("Every snapshot document embeds oais.provenance.signature: Ed25519 over the canonical statement bytes in the tree-head domain. Rebuild the bytes per the discovery document's notarization recipe and verify with unidpp_signatif SignatureSlot::verify against this `public` anchor."),
        );
        if let Some(seed) = &self.dev_seed {
            m.insert("dev_seed".into(), json!(seed));
            m.insert(
                "warning".into(),
                json!("seeded-dev mode is for development only; production deployments must use env-key mode"),
            );
        }
        Value::Object(m)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn dev_mode_is_deterministic_and_seed_sensitive() {
        let a = Keyring::dev(Some("test-seed"));
        let b = Keyring::dev(Some("test-seed"));
        let c = Keyring::dev(Some("other-seed"));
        assert_eq!(a.mode(), KeyringMode::SeededDev);
        assert_eq!(a.key_id(), b.key_id());
        assert_eq!(a.public_hex(), b.public_hex());
        assert_ne!(a.key_id(), c.key_id());
        assert_eq!(a.public().suite(), Suite::Ed25519);
    }

    #[test]
    fn empty_seed_falls_back_to_default() {
        let k = Keyring::dev(Some(""));
        assert_eq!(k.dev_seed(), Some(DEFAULT_DEV_SEED));
        assert_eq!(k.mode(), KeyringMode::SeededDev);
        // Unset behaves the same as empty.
        assert_eq!(
            Keyring::dev(None).public_hex(),
            Keyring::dev(Some("")).public_hex()
        );
    }

    #[test]
    fn env_mode_round_trip_and_distinct_from_dev() {
        let seed = "0011223344556677889900aabbccddeeff00112233445566778899aabbccddee";
        let k = Keyring::from_env_seed(seed).unwrap();
        assert_eq!(k.mode(), KeyringMode::EnvKey);
        assert!(k.dev_seed().is_none());
        // The seed is hashed into the key, so the public re-derives
        // from it and differs from the dev default.
        let re = KeyPair::seeded(Suite::Ed25519, &hex_decode(seed).unwrap()).unwrap();
        assert_eq!(k.public_hex(), hex_encode(re.public().as_bytes()));
        assert_ne!(k.public_hex(), Keyring::dev(None).public_hex());
    }

    #[test]
    fn env_mode_rejects_short_and_bad_hex() {
        let short = "deadbeef";
        assert!(Keyring::from_env_seed(short).is_err());
        assert!(Keyring::from_env_seed("nonsense!!").is_err());
        assert!(Keyring::from_env_seed("").is_err());
    }

    #[test]
    fn public_hex_is_the_32_byte_ed25519_anchor() {
        let k = Keyring::dev(Some("anchor-test"));
        assert_eq!(k.public_hex().len(), 64); // 32 bytes hex
        assert_eq!(k.public().as_bytes().len(), 32);
    }

    #[test]
    fn to_json_includes_anchor_recipe_and_warning() {
        let k = Keyring::dev(Some("j"));
        let v = k.to_json();
        assert_eq!(v["mode"], "seeded-dev");
        assert_eq!(v["suite"], "ed25519");
        assert_eq!(v["public_len"], 32);
        assert_eq!(v["domain"], "tree-head");
        assert!(v["warning"].as_str().unwrap().contains("seeded-dev"));
        assert!(v["adapter_note"].as_str().unwrap().contains("tree-head"));
        // env-key mode has no warning.
        let env = Keyring::from_env_seed(
            "0011223344556677889900aabbccddeeff00112233445566778899aabbccddee",
        )
        .unwrap();
        assert!(env.to_json().get("warning").is_none());
    }
}
